### ISSUE TITLE
galera.cnf - Mandatory variable 'ansible_ens192'  not defined

### ISSUE THREAD

**Issue by thesefer** [mrlesmithjr/ansible-mariadb-galera-cluster#231]
**Describe the bug**
Setting up a node I receive an error about `ansible_ens192` not being defined.

**To Reproduce**
Commit: a83a130b1b2f251a36bde312d0e327a2c9211ce1
```
mariadb_version: "10.6.18"
galera_enable_mariadb_repo: false
galera_cluster_bind_interface: "{{ ansible_default_ipv4['interface'] }}"
galera_cluster_name: "icinga-db-cluster"
galera_cluster_nodes_group: "test_services"
galera_mysql_first_node: "{{ groups[galera_cluster_nodes_group][0] }}"
mariadb_charset_server: utf8mb4
mariadb_collation_server: "utf8mb4_unicode_ci"
mariadb_charset_client: utf8mb4
mariadb_databases:
  - name: icingadb
  - name: icingaweb
  - name: vspheredb
  - name: "{{ icingaweb2_resources['director_db']['dbname'] }}"
mariadb_mysql_users:
  - name: icingaweb
    hosts:
      - "%"
    password: "{{ icingaweb2_db['password'] }}"
    priv: "icingaweb.*:ALL"
  - name: icingadb
    hosts:
      - "%"
    password: "{{ icingadb_database_password }}"
    priv: "icingadb.*:ALL"
  - name: vspheredb
    hosts:
      - "%"
    password: "abcdefg"
    priv: "vspheredb.*:ALL"
  - name: "{{ icingaweb2_resources['director_db']['username'] }}"
    hosts:
      - "%"
    password: "{{ icingaweb2_resources['director_db']['password'] }}"
    priv: "{{ icingaweb2_resources['director_db']['dbname'] }}.*:ALL"
```

**Expected behavior**
No errors

**Error**
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/ansible/plugins/action/template.py", line 151, in run
    resultant = templar.do_template(template_data, preserve_trailing_newlines=True, escape_backslashes=False, overrides=overrides)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ansible/template/__init__.py", line 993, in do_template
    res = myenv.concat(rf)
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ansible/template/native_helpers.py", line 81, in ansible_concat
    return ''.join([to_text(v) for v in nodes])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 149, in root
  File "/usr/local/lib/python3.12/dist-packages/ansible/template/__init__.py", line 294, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/ansible/plugins/filter/core.py", line 337, in mandatory
    raise AnsibleFilterError("Mandatory variable %s not defined." % name)
ansible.errors.AnsibleFilterError: Mandatory variable 'ansible_ens192'  not defined.
failed: [domain.net] (item={'name': 'etc/mysql/conf.d/galera.cnf'}) => {
    "ansible_loop_var": "file",
    "changed": false,
    "file": {
        "name": "etc/mysql/conf.d/galera.cnf"
    },
    "msg": "AnsibleFilterError: Mandatory variable 'ansible_ens192'  not defined."
}
```

**Additional context**
Target: Ubuntu 22
Host: Ubuntu 24 with ansible 10.5.0
```
ansible [core 2.17.5]
  config file = /ansible/ansible.cfg
  configured module search path = ['/ansible/modules']
  ansible python module location = /usr/local/lib/python3.12/dist-packages/ansible
  ansible collection location = /ansible/collections/ansible_collections:/root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

`ansible domain.net -m ansible.builtin.setup` Result
```
        "ansible_ens192": {
            "active": true,
            "device": "ens192",
[...]
            "ipv4": {
                "address": "192.168.0.25",
                "broadcast": "192.168.0.255",
                "netmask": "255.255.255.0",
                "network": "192.168.0.0/",
                "prefix": "24"
            },
[...]
```

**Comment by thesefer** [comment]
Totally misunderstood how this role is supposed to run. Not against each host but a group at once.
